--Initialization script:
-------------------------------------------
--INSERT INTO tbl_category (id, name, description, rating_form) VALUES (1, 'Book', 'Ratings of books you have read or books you are planning to read', 'STARS');
--INSERT INTO tbl_category (id, name, description, rating_form) VALUES (2, 'Game', 'Ratings of computer/consol games you have played or games you are planning to play.', 'STARS');
--INSERT INTO tbl_category (id, name, description, rating_form) VALUES (3, 'Movie', 'Ratings of movies you have watched or movies you are planning to watch.', 'STARS');
--INSERT INTO tbl_category (id, name, description, rating_form) VALUES (4, 'Series', 'Ratings of series you have watched or series you are planning to watch.', 'STARS');
--
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (1, 'Characters');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (1, 'Pacing');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (1, 'Plot');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (1, 'World');
--
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (2, 'Content amount');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (2, 'Gameplay');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (2, 'Graphic');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (2, 'Plot');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (2, 'Soundtrack');
--
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (3, 'Action');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (3, 'Effects');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (3, 'Music');
--INSERT INTO tbl_category_factors (category_id, factor) VALUES (3, 'Plot');